/* Generated by: JJTree: Do not edit this line. Action.java Version 1.1 */
/* ParserGeneratorCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.patex.lrequest;

import java.util.function.Function;
import java.util.function.Supplier;

public
class Action extends SimpleNode {

  public Action(int id) {
    super(id);
  }

  public Action(LibRequestBuilder p, int id) {
    super(p, id);
  }

  public ActionHandler getFunction(ActionHandlerStorage builder) {
    return builder.getAction((String) jjtGetValue());
  }

  public RequestResult[] getParams(ActionHandlerStorage builder) {
    RequestResult[] params = new RequestResult[jjtGetNumChildren()];

    for (int i = 0; i < jjtGetNumChildren(); i++) {
      params[i]= ((ValueSupplier) jjtGetChild(i)).getValueSupplier(builder);
    }
    return params;
  }
}
/* ParserGeneratorCC - OriginalChecksum=362c6b7426f3edb783c45a9947662f69 (do not edit this line) */
