/* Generated by: JJTree: Do not edit this line. FindAuthor.java Version 1.1 */
/* ParserGeneratorCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.patex.lrequest;

import lombok.Data;

@Data
public class FindAuthor extends SimpleNode {
  public FindAuthor(int id) {
    super(id);
  }

  private String authorName;

  public FindAuthor(LibRequestBuilder p, int id) {
    super(p, id);
  }
}
/* ParserGeneratorCC - OriginalChecksum=009f584c6a585ac7e84077f2c7af4b75 (do not edit this line) */
