/* Generated by: JJTree: Do not edit this line. Param.java Version 1.1 */
/* ParserGeneratorCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.patex.lrequest;

public class Param extends DummyNode{


  public Param(int i) {
    super(i);
  }

  private String name;
  private String value;

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }
}
/* ParserGeneratorCC - OriginalChecksum=a7183786daeef5b0fe1d87da8fb951ee (do not edit this line) */
