/* Generated by: JJTree: Do not edit this line. Request.java Version 1.1 */
/* ParserGeneratorCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.patex.lrequest;

import java.util.function.Function;
import java.util.function.Supplier;

public
class Request extends SimpleNode implements ValueSupplier {

  public Request(int id) {
    super(id);
  }

  public Request(LibRequestBuilder p, int id) {
    super(p, id);
  }

  @Override
  public Supplier getValueSupplier(ActionHandlerStorage handlerStorage) {
    Function result = o -> o;
    for (int i = 0; i < jjtGetNumChildren(); i++) {
      Action action = (Action) jjtGetChild(i);
      result=result.andThen(action.getFunction(handlerStorage));
    }
    Function r=result;
    return ()->r.apply(null);
  }
}
/* ParserGeneratorCC - OriginalChecksum=a48974d8142e543c3be7b9546cd90bc3 (do not edit this line) */
