server:
  port: 8090
jwt:
  secret: "VERY_BIG_SECRET"
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/
localStorage:
  folder: './storage'
spring:
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB