/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    id("org.springframework.boot") version "4.1.0"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

}

springBoot{

    //mainClassName="com.patex.Application"
}
tasks.getByName<org.springframework.boot.gradle.tasks.bundling.BootJar>("bootJar") {
    mainClass.set("com.patex.forever.Application")
    this.archiveFileName.set("foreverCore.jar")
}

val springBootVersion: String by rootProject.extra
dependencies {
    api(project(":core"))
    api(project(":opds"))
    api(project(":data-storage"))
    api("org.glassfish.jaxb:jaxb-runtime:4.0.9")
    api("org.postgresql:postgresql:42.7.11")
    testImplementation("org.junit.jupiter:junit-jupiter:6.0.3")
    testImplementation("org.junit.jupiter:junit-jupiter-api:6.0.3")
    testImplementation("org.springframework.boot:spring-boot-starter-test:$springBootVersion")
    testImplementation("com.patex:fb2-java:1.0")
}

group = "com.patex.foreverlib"
version = "0.39-SNAPSHOT"
description = "exec"
java.sourceCompatibility = JavaVersion.VERSION_25

tasks.withType<Test> {
    failOnNoDiscoveredTests = false
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
