/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    id("org.springframework.boot") version "2.0.1.RELEASE"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

}

springBoot{

    mainClassName="com.patex.Application"
}
tasks.getByName<org.springframework.boot.gradle.tasks.bundling.BootJar>("bootJar") {
    this.archiveFileName.set("zombieCore.jar")
}

dependencies {
    api(project(":core"))
    api(project(":opds"))
    api(project(":data-storage"))
    api("org.glassfish.jaxb:jaxb-runtime:3.0.1")
    api("org.postgresql:postgresql:42.3.1")
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.2")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.2")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.6.2")
    testImplementation("com.patex:fb2-java:0.2")
}

group = "com.patex.zombielib2"
version = "0.39-SNAPSHOT"
description = "exec"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
