//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.10.10 at 08:33:42 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.gribuser.ru/xml/fictionbook/2.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fb2;
