//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.10.10 at 08:33:42 PM CEST 
//


package fb2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for shareModesType.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="shareModesType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="free"/&gt;
 *     &lt;enumeration value="paid"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "shareModesType")
@XmlEnum
public enum ShareModesType {

    @XmlEnumValue("free")
    FREE("free"),
    @XmlEnumValue("paid")
    PAID("paid");
    private final String value;

    ShareModesType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ShareModesType fromValue(String v) {
        for (ShareModesType c: ShareModesType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
