/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

}

dependencies {
    api(project(":common"))
    api("com.rometools:rome:1.17.0")
    api("org.springframework:spring-aspects:5.3.14")
    api("org.springframework:spring-context:5.3.14")
    api("org.springframework:spring-webmvc:5.3.14")
    api("org.springframework.security:spring-security-core:5.6.1")
    api("org.springframework.data:spring-data-commons:2.6.0")
    api("org.springframework.boot:spring-boot-starter-data-jpa:2.6.2")
    api("org.apache.tomcat.embed:tomcat-embed-core:9.0.56")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.6.2")
    testImplementation("com.patex:fb2-java:0.2")
    testImplementation("org.apache.commons:commons-lang3:3.12.0")
    testImplementation("org.apache.commons:commons-text:1.9")
    compileOnly("org.projectlombok:lombok:1.18.24")
    annotationProcessor("org.projectlombok:lombok:1.18.24")
    testCompileOnly("org.projectlombok:lombok:1.18.24")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.24")
}

group = "com.patex.zombielib2"
version = "0.39-SNAPSHOT"
description = "opds"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
