/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

}
val springVersion: String by rootProject.extra
val springBootVersion: String by rootProject.extra
dependencies {
    api(project(":common"))
    api("com.rometools:rome:1.17.0")

    compileOnly("jakarta.servlet:jakarta.servlet-api:6.0.0")

    api("org.springframework:spring-aspects:$springVersion")
    api("org.springframework:spring-context:$springVersion")
    api("org.springframework:spring-webmvc:$springVersion")
    api("org.springframework.security:spring-security-core:$springVersion")
    api("org.springframework.data:spring-data-commons:3.1.4")
    api("org.springframework.boot:spring-boot-starter-data-jpa:$springBootVersion")
    testImplementation("org.springframework.boot:spring-boot-starter-test:$springBootVersion")
    testImplementation("com.patex:fb2-java:1.0")
    testImplementation("org.apache.commons:commons-lang3:3.12.0")
    testImplementation("org.apache.commons:commons-text:1.10.0")
    compileOnly("org.projectlombok:lombok:1.18.24")
    annotationProcessor("org.projectlombok:lombok:1.18.24")
    testCompileOnly("org.projectlombok:lombok:1.18.24")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.24")
}

group = "com.patex.zombielib2"
version = "0.39-SNAPSHOT"
description = "opds"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
