/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}
val springBootVersion: String by rootProject.extra
val springVersion: String by rootProject.extra
val springSecurityVersion: String by rootProject.extra
val lombokVersion: String by rootProject.extra

dependencies {
    api("org.springframework.data:spring-data-commons:$springBootVersion")
    api("com.fasterxml.jackson.core:jackson-annotations:2.20")
    api("org.springframework:spring-context:$springVersion")
    api("com.patex:plural-resource-bundle:0.0.4")
    api("org.springframework.boot:spring-boot-autoconfigure:$springBootVersion")
    api("org.telegram:telegrambots:6.9.7.1")
    api("org.springframework:spring-tx:$springVersion")
    api("org.springframework.security:spring-security-core:$springSecurityVersion")
    compileOnly("org.projectlombok:lombok:$lombokVersion")
    implementation("jakarta.annotation:jakarta.annotation-api:3.0.0")
    api("com.google.guava:guava:33.6.0-jre")

    annotationProcessor("org.projectlombok:lombok:$lombokVersion")
    testCompileOnly("org.projectlombok:lombok:$lombokVersion")

}

group = "com.patex.foreverlib2"
version = "0.39-SNAPSHOT"
description = "common"
java.sourceCompatibility = JavaVersion.VERSION_25

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
