/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}
val springBootVersion: String by rootProject.extra
val springVersion: String by rootProject.extra
dependencies {
    api("org.springframework.data:spring-data-commons:$springBootVersion")
    api("com.fasterxml.jackson.core:jackson-annotations:2.13.1")
    api("org.springframework:spring-context:$springVersion")
    api("com.patex:plural-resource-bundle:0.0.2")
    api("jakarta.annotation:jakarta.annotation-api:1.3.5")
    api("org.springframework.boot:spring-boot-autoconfigure:$springBootVersion")
    api("org.telegram:telegrambots:5.6.0")
    api("org.springframework:spring-tx:$springVersion")
    api("org.springframework.security:spring-security-core:5.6.1")
    compileOnly("org.projectlombok:lombok:1.18.24")
    annotationProcessor("org.projectlombok:lombok:1.18.24")
    testCompileOnly("org.projectlombok:lombok:1.18.24")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.24")
}

group = "com.patex.zombielib2"
version = "0.39-SNAPSHOT"
description = "common"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
