/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}
val lombokVersion: String by rootProject.extra

dependencies {
    api(project(":common"))
    annotationProcessor("org.projectlombok:lombok:$lombokVersion")
    implementation("jakarta.annotation:jakarta.annotation-api:2.1.1")
    testCompileOnly("org.projectlombok:lombok:$lombokVersion")
    testAnnotationProcessor("org.projectlombok:lombok:$lombokVersion")
    testImplementation("org.junit.jupiter:junit-jupiter:6.0.3")
    testImplementation ("org.junit.jupiter:junit-jupiter-api:6.0.3")
    testRuntimeOnly ("org.junit.jupiter:junit-jupiter-engine:6.0.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:6.0.3")
    testImplementation("org.mockito:mockito-core:5.23.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.23.0")
}

group = "com.patex.foreverlib2"
version = "0.39-SNAPSHOT"
description = "data-storage"
java.sourceCompatibility = JavaVersion.VERSION_25

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
tasks.withType<Test>() {
    useJUnitPlatform()
}

