spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    hikari:
      maximum-pool-size: 20
  rabbitmq:
    listener:
      direct:
        prefetch: 10
      simple:
        prefetch: 10
  jpa:
    database-platform:  org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db-changelog.main.xml
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
localStorage:
  folder: ./storage
  bulk-upload:
    folder:
telegram:
  bot:
    token:
  name:
  baseurl:
duplicateCheck:
  threadCount: 0
  shingleCoeff: 1
  fastCacheSize: 100
  storageCacheFolder:
extlib:
  connection:
    timeout: 300
